### ISSUE TITLE
crashes if switching workspace very fast

### ISSUE THREAD

**Issue by xuhdev** [denesb/xfce4-i3-workspaces-plugin#9] opened 2014-12-27 06:43 UTC
I binded Ctrl-<number> to switch to workspace <number>. If I switch very fast, e.g. press Ctrl 8 and 9 almost simultaneously, this plugin would crash.

**Comment by denesb** [comment] 2015-01-03 14:20
I tried but couldn't reproduce this, although I experienced some weird crashes myself. For example at one time I noticed that the plugin would crash every time I switch to the workspace 3.
I will keep looking for the reason behind these crashes.

**Comment by denesb** [comment] 2015-02-23 16:26
I could not reproduce this since long. I'm closing it. If you still encounter it, please reopen the issue.

**Closed by denesb** 2015-02-23 16:26 UTC
Labels: bug
